### ISSUE TITLE
Add Support for SSL CA cert files

### ISSUE THREAD

**Issue by nathanmcgarvey** [exoscale/cs#122]
Looks like documentation doesn't line up with code implementation:

https://github.com/exoscale/cs/blob/229e0c166d77da24d3608aa2b0abc92a87ee69cb/README.rst
....has "CLOUDSTACK_VERIFY" as an optional parameter, but I can't find it implemented anywhere.

Looks like some other folks ran into the same issue from a fork:
    https://github.com/ngine-io/ansible-collection-cloudstack/pull/3

**Comment by brutasse** [comment]
Closing as invalid, `CLOUDSTACK_VERIFY` is valid, implemented and works as expected.
