### ISSUE TITLE
Support POST for larger userdata in deployVirtual Machine

### ISSUE THREAD

**Issue by synergiator** [exoscale/cs#128]
According to [API documentation](https://cloudstack.apache.org/api/apidocs-4.18/apis/deployVirtualMachine.html), userdata parameter can be allowed to be large with POST method.

In the existing clients, this has not been supported: CloudMonkey implements this only in the upcoming release [6.4.0](https://github.com/apache/cloudstack-cloudmonkey/issues/139).

Also, this Python client seems to user GET, also when userdata parameter is larger than 8K:
```
send: b'GET /client/api?projectid=0..1fa&userdata=zoK...wOQ&...
command=deployVirtualMachine&response=json&signatureVersion=3&
expires=2023-11-13T19%3A12%3A09%2B0000&signature=so..Q5n4%3D
HTTP/1.1\r\nHost: XXXXX\r\nAccept-Encoding: identity\r\nUser-Agent: python-urllib3/2.0.7\r\n\r\n'
```

**Comment by greut** [comment]
try `cs = CloudStack(..., method='post')`, cf. https://github.com/exoscale/cs/blob/master/cs/client.py#L203

**Comment by synergiator** [comment]
thx
