### ISSUE TITLE
Need a user-agent name defined, so it's more secure

### ISSUE THREAD

**Issue by CodeBleu** [exoscale/cs#129]
We have some WAF Bot mitigation that is blocking and banning IPs that are  based on the `user-agent` that is being passed 
`python-urllib3/1.26.5`  Can you update the default agent to something else besides the `none` that is being used and hence using the default  `python-urllib3/1.26.5`

Maybe there is a better place to put this, but in my testing i just modified this section of code and added a user agent here and was able to successfully use it without my WAF blocking it.

https://github.com/exoscale/cs/blob/master/cs/client.py#L214

Suggested default agent name: `exoscale-cs`

**Comment by sauterp** [comment]
Hi,

thank you for raising this.

Exoscale is going to move away from the [cloudstack API](https://changelog.exoscale.com/en/deprecation-api-v1-as-of-may-1st-2024-uVYHUVZ3).

Please use our new python library https://github.com/exoscale/python-exoscale
