### ISSUE TITLE
Environment variables do not work

### ISSUE THREAD

**Issue by jeffallen** [exoscale/cs#30]
If you try to use only env vars to config it, you get:

Config file not found. Tried /Users/marina/.cloudstack.ini, /Users/marina/entuu\
ra/cloudstack.ini

If you put an empty .cloudstack.ini there to shut it up, you get:

Error: region 'cloudstack' not in config

**Comment by marcaurele** [comment]
Hi jeff, thanks for the heads up. It's actually a misspelling in the name of one environment variable on the blog post. You should set **`CLOUDSTACK_SECRET`** instead of `CLOUDSTACK_SECRET_KEY`. The README on github is correct and we'll fix the blog post.
