### ISSUE TITLE
How to tell cs to use proxy?

### ISSUE THREAD

**Issue by 1605200517** [exoscale/cs#78]
CS incorporates the requests library which supports proxies.

http://docs.python-requests.org/en/latest/api/#module-requests

How can I pass the proxy confguration to it through cs?

In a proxy environment, the library does not seem to read in standard system http_proxy variables.

**Comment by greut** [comment]
taking a closer look at it, it seems to be supported by requests,

http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by 1605200517** [comment]
indeed, you're right! thanks

**Comment by greut** [comment]
Cheers,
