### ISSUE TITLE
Test environments for cs

### ISSUE THREAD

**Issue by synergiator** [exoscale/cs#81]
How do you test this component also for cross-compatibility?

I've checked for community Docker images of Apache Cloud Stack but for example for 4.7 /4.9/4.10 there are no images available and the provided Dockerfile does not build.

See also:
https://github.com/apache/cloudstack/issues/3083

**Comment by greut** [comment]
did you try @resmo's https://github.com/resmo/cloudstack-test-container ?

**Comment by resmo** [comment]
It is a integration test environment setup for ansible modules (which also rely on cs):
~~~
docker run -d -p 8888:8888 --name cloudstack-sim quay.io/ansible/cloudstack-test-container:1.2.0
~~~
This takes a minute or 2. You can check the URL http://localhost:8888/admin.json, it returns a 503 unless all is set up. When setup completed you get root admin api keys from the location.

Default UI login is also available at http://localhost:8888/client/ with `admin` and `password` as credentials.

**Comment by 1605200517** [comment]
@greut @resmo 
thanks for providing the resources, however:

* @resmo's Dockerfile linked by @greut integrates version 4.9
https://github.com/resmo/cloudstack-test-container/blob/master/Dockerfile

* @resmo's link to quay project integrates version 4.11
https://github.com/ansible/cloudstack-test-container/blob/master/Dockerfile

I'd have a go and try to change the first position from 4.9 to 4.7, maybe I'm lucky.
