### ISSUE TITLE
How to use createTags?

### ISSUE THREAD

**Issue by 1605200517** [exoscale/cs#99]
The API method createTags() requires a parameter "tags" as [_map of tags (key/value pairs)_](https://cloudstack.apache.org/api/apidocs-4.10/apis/createTags.html) to be passed.

However for the following call I get an error as listed below.

```
tagsresult = self.cs.createTags(resourceids=mynetwork_id, resourcetype="Network", 
tags={"foo":"bar"})

530 - Value for the key null is either null or empty

```

Do I have to use some another notation to pass the tags?

**Comment by greut** [comment]
It's harder than that, try `tags=[{"key": "foo", "value": "bar"}]`

**Comment by 1605200517** [comment]
awesome, thank you!
